#          _____                    _____                    _____
#         /\    \                  /\    \                  /\    \
#        /::\____\                /::\    \                /::\____\
#       /:::/    /               /::::\    \              /:::/    /
#      /:::/    /               /::::::\    \            /:::/    /
#     /:::/    /               /:::/\:::\    \          /:::/    /
#    /:::/____/               /:::/  \:::\    \        /:::/____/
#   /::::\    \              /:::/    \:::\    \      /::::\    \
#  /::::::\____\________    /:::/    / \:::\    \    /::::::\____\________
# /:::/\:::::::::::\    \  /:::/    /   \:::\ ___\  /:::/\:::::::::::\    \
# \:::/  |:::::::::::\____\/:::/____/  ___\:::|    |/:::/  |:::::::::::\____\
#  \::/   \:::\~~~~\~~~~~~~            /\  \::|    | \::/   \:::\~~~~\~~~~~~
#   \/____/\:::\    \                  /::\ |::|    |  \/____/\:::\    \
#           \:::\    \                /::::\|::|    |          \:::\    \
#            \:::\    \              /::::::|::|    |           \:::\    \
#             \:::\____\            /:::/\:::|____|            \:::\____\
#              \::/    /            \::/  \::/    /             \::/    /
#               \/____/              \/____\/____/               \/____/

#This file stores the items that have been placed inside the inventory incase your server must go down.